apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 80Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # Retain : pod가 삭제되었다 떠도 볼륨 유지
  # Delete : pod가 삭제되었다 뜨면 빈상태로 시작
  # Recycle : rm -rf /&로 모든 데이터 삭제
  # 만약 mongo에서 mysql로 바꿀땐 Retain 대부분 Retain을 많이 쓴다.
  # 3개를 결정하는 요인은 stateful이냐 stateless인가로 결 정된다.
  # stateful -> 뭔가 저장된다 싶으면 stateful
  # stateless -> redis를 통해 redis에 다 저장
  # aws driver 설정 google이나 azure에서는 설정할 필요없이 자동으로 되어있다.
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0d657c8e2b19a1905
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: topology.ebs.csi.aws.com/zone
            operator: In
            values:
            - ap-northeast-2a
