apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-dynamic
spec:
  resources:
    requests:
      storage: 80Gi
  volumeMode: Filesystem
  # ebs는 RWO밖에 안된다 efs를 써야 write도 가능
  accessModes:
    - ReadWriteOnce
  storageClassName: "fast"