apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 80Gi
  volumeMode: Filesystem
  # ebs는 RWO밖에 안된다 efs를 써야 write도 가능
  accessModes:
    - ReadWriteOnce
  # ""는 기본 sc를 사용
  storageClassName: ""