apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  labels:
    name: apache
    tier: frontend
    app: apache
spec:
  containers:
  - name: apache-container
    image: bitnami/apache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
# apiVersion: v1
# kind: Pod
# metadata:
#   name: apache-pod
#   labels:
#     name: apache
#     tier: FronEnd
#     app: apache
# spec:
#   nodeSelector:
#     memsize: "high"
#   containers:
#   - name: goapp
#     image: bitnami/apache
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 8080
